name: Build Atomik PHP
on:
  push:
    branches:
      - main
    paths:
      - "containerapps/php/**"
      - ".github/workflows/build-php.yml"
  pull_request:
    branches:
      - main
    paths:
      - "containerapps/php/**"
      - ".github/workflows/build-php.yml"
  workflow_dispatch:
env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  build-php:
    name: Build php
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Set image metadata
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: ${{ env.IMAGE_REGISTRY }}/atomik-php
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix=sha-
      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        id: build
        uses: redhat-actions/buildah-build@719e3c40d8af9790c23eca13f7daa339f2867034 # v3.1.0
        with:
          image: atomik-php
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          containerfiles: ./containerapps/php/Containerfile
          oci: true
      - name: Push image
        uses: redhat-actions/push-to-registry@94ade333c38ecc0e60e94785125d9a52ca423b37 # v3.0.0
        id: push
        with:
          tags: ${{ steps.build.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install cosign
        uses: sigstore/cosign-installer@398d4b0eeef1380460a10c8013a76f728fb906ac # v3.9.1
        if: github.event_name != 'pull_request'
      - name: Sign the image
        if: github.event_name != 'pull_request'
        run: |
          cosign sign --yes ${{ env.IMAGE_REGISTRY }}/atomik-php@${{ steps.push.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: true